salary_caluclation: salary_calulation.o
                g++ salary_calculation.o -o salary_calculation
salary_calculation.o: salary_calculation.cpp
                g++ salary_calculation.cpp -o salary_calculation.o
run: salary_calculation
    ./salary_calculation

clean:
    rm -f salary_calculation.o salary_calculation
