all:
    g++ -o quadequationrealorfake quadequationrealorfake.cpp
dump:
    objdump -d quadequationrealorfake > quadequationrealorfake.asm

clean:
    rm -f quadequationrealorfake quadequation.asm
run: quadequationrealorfake
                ./quadequationrealorfake
